"""
Plugin Generator CLI.

Usage:
    python -m app.plugins.cli generate my_tool --type tool --author "Jane Dev"

Scaffolds dev_plugins/<name>/ with a manifest.json, a plugin.py containing a
PluginBase subclass skeleton for the chosen type, and a README explaining
next steps (fill in register(), then package manifest+code into a
marketplace listing's inline asset bundle to publish — see
app/marketplace/security.py's checksum/secret-scan for what publishing
validates).

Python (not the frontend's Node/CJS tools/*.cjs convention) — this is a
backend Python SDK; a plugin author writing Python has no reason to go
through the Vite build toolchain's tooling, which is scoped to frontend
asset building, not backend plugin authoring.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from app.plugins.base import PluginType

_REPO_ROOT = Path(__file__).parent.parent.parent
_DEV_PLUGINS_DIR = _REPO_ROOT / "dev_plugins"

_ENTRY_CLASS_TEMPLATES: dict[PluginType, str] = {
    PluginType.TOOL: '''\
class {class_name}(PluginBase):
    plugin_type = PluginType.TOOL

    def register(self, ctx: PluginContext) -> None:
        from app.ai.models import ToolSchema
        from app.plugins.adapters import adapt_tool

        schema = ToolSchema(
            name="{plugin_id}",
            description="TODO: describe what this tool does",
            parameters={{"type": "object", "properties": {{}}, "required": []}},
        )

        def handler(**kwargs):
            return {{"result": "TODO: implement"}}

        adapt_tool(schema, handler)

    def unregister(self, ctx: PluginContext) -> None:
        from app.plugins.adapters import unadapt_tool
        unadapt_tool("{plugin_id}")
''',
    PluginType.EVENT_LISTENER: '''\
class {class_name}(PluginBase):
    plugin_type = PluginType.EVENT_LISTENER

    def __init__(self) -> None:
        self._pattern = "job.completed"
        self._handler = None

    def register(self, ctx: PluginContext) -> None:
        from app.plugins.adapters import adapt_event_listener

        async def handler(event) -> None:
            ctx.logger.info("received event: %s", event)

        self._handler = handler
        adapt_event_listener(self._pattern, handler)

    def unregister(self, ctx: PluginContext) -> None:
        from app.plugins.adapters import unadapt_event_listener
        if self._handler is not None:
            unadapt_event_listener(self._pattern, self._handler)
''',
    PluginType.WORKFLOW_NODE: '''\
class {class_name}(PluginBase):
    plugin_type = PluginType.WORKFLOW_NODE

    def register(self, ctx: PluginContext) -> None:
        from app.plugins.adapters import adapt_workflow_node

        async def node(**kwargs):
            return {{"result": "TODO: implement"}}

        adapt_workflow_node("{plugin_id}", node)

    def unregister(self, ctx: PluginContext) -> None:
        from app.plugins.adapters import unadapt_workflow_node
        unadapt_workflow_node("{plugin_id}")
''',
}

_DEFAULT_TEMPLATE = '''\
class {class_name}(PluginBase):
    plugin_type = PluginType.{type_enum_name}

    def register(self, ctx: PluginContext) -> None:
        # TODO: wire this plugin into the platform — see app/plugins/adapters.py
        # for the registration helper matching this plugin's type.
        ctx.logger.info("{plugin_id} registered")
'''

_PLUGIN_PY_HEADER = '''\
"""
{plugin_id} — generated by `python -m app.plugins.cli generate`.

This file is loaded standalone by the Plugin Loader (importlib, isolated
module namespace) — it must not import anything from app.* other than the
Plugin SDK itself (app.plugins.*) and, inside register(), the specific
adapter/registry module it needs. See app/plugins/base.py for the full
PluginBase/PluginContext API.
"""
from app.plugins.base import PluginBase, PluginContext, PluginType


'''


def _manifest_json(plugin_id: str, name: str, author: str, description: str, plugin_type: PluginType) -> str:
    import json
    return json.dumps({
        "id": plugin_id, "name": name, "version": "1.0.0", "author": author,
        "description": description, "category": plugin_type.value,
        "dependencies": [], "required_permissions": [],
        "min_platform_version": "1.0.0", "max_platform_version": None,
        "entry_point": f"plugin:{_class_name(plugin_id)}",
        "configuration_schema": {},
    }, indent=2)


def _class_name(plugin_id: str) -> str:
    return "".join(part.capitalize() for part in plugin_id.replace("-", "_").split("_")) + "Plugin"


def generate(plugin_id: str, *, plugin_type: PluginType, author: str, description: str) -> Path:
    from app.plugins.manifest import _ID_RE
    if not _ID_RE.match(plugin_id):
        raise SystemExit(
            f"error: {plugin_id!r} is not a valid plugin id — must match {_ID_RE.pattern} "
            "(lowercase alphanumeric, '_', '-', 3-64 chars, starting with a letter/digit)"
        )
    out_dir = _DEV_PLUGINS_DIR / plugin_id
    if out_dir.exists():
        raise SystemExit(f"error: {out_dir} already exists")
    out_dir.mkdir(parents=True)

    class_name = _class_name(plugin_id)
    template = _ENTRY_CLASS_TEMPLATES.get(plugin_type, _DEFAULT_TEMPLATE)
    body = template.format(class_name=class_name, plugin_id=plugin_id, type_enum_name=plugin_type.name)

    (out_dir / "manifest.json").write_text(
        _manifest_json(plugin_id, plugin_id.replace("_", " ").title(), author, description, plugin_type),
        encoding="utf-8",
    )
    (out_dir / "plugin.py").write_text(_PLUGIN_PY_HEADER.format(plugin_id=plugin_id) + body, encoding="utf-8")
    (out_dir / "README.md").write_text(
        f"# {plugin_id}\n\n"
        f"A {plugin_type.value} plugin scaffolded by `python -m app.plugins.cli generate`.\n\n"
        "## Next steps\n\n"
        "1. Fill in `register()` (and `unregister()`, if your plugin type needs cleanup) in `plugin.py`.\n"
        "2. Fill in `required_permissions` in `manifest.json` with any of the declared capabilities "
        "your code actually needs (see app/marketplace/security.py's ALL_KNOWN_CAPABILITIES).\n"
        "3. To publish: bundle manifest.json + plugin.py's contents into a marketplace listing's "
        "inline asset as `{\"manifest\": <manifest.json contents>, \"code\": \"<plugin.py contents>\"}` "
        "via `POST /marketplace/listings` with `type=plugin`.\n",
        encoding="utf-8",
    )
    return out_dir


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m app.plugins.cli")
    sub = parser.add_subparsers(dest="command", required=True)

    gen = sub.add_parser("generate", help="Scaffold a new plugin under dev_plugins/")
    gen.add_argument("plugin_id", help="Lowercase id, e.g. my_tool")
    gen.add_argument("--type", choices=[t.value for t in PluginType], default=PluginType.TOOL.value)
    gen.add_argument("--author", default="anonymous")
    gen.add_argument("--description", default="A new plugin.")

    args = parser.parse_args(argv)
    if args.command == "generate":
        out_dir = generate(
            args.plugin_id, plugin_type=PluginType(args.type),
            author=args.author, description=args.description,
        )
        print(f"Scaffolded {out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
