import base64
import json
import shutil
from pathlib import Path
from typing import Optional

from fastapi import APIRouter
from fastapi.responses import FileResponse, StreamingResponse
from pydantic import BaseModel

from app.core.config import DIST_DIR
from app.core.filesystem import workspace
from app.core.helpers import sanitize_name
from app.runtime import registry
from app.runtime import process as rt_process
from app.runtime.preflight import run_preflight, preflight_error_events
from app.runtime.errors import sse_error

router = APIRouter(tags=["package"])


@router.get("/api/package/runtimes")
async def get_runtimes():
    """Return the runtime registry — which tools are available on this machine."""
    return registry.to_dict()


class PackageRequest(BaseModel):
    project_id: str
    target:      str  = "exe"
    lang:        str  = "python"
    app_name:    str  = "MyApp"
    app_version: str  = "1.0.0"
    one_file:    bool = True
    console:     bool = False


async def _run_stream(cmd: list, cwd: str):
    """Delegate to the unified runtime process API. Interface unchanged."""
    async for line, code in rt_process.stream_process(cmd, cwd=cwd):
        yield line, code


@router.post("/api/package/stream")
async def package_stream(req: PackageRequest):
    ws        = workspace(req.project_id)
    safe_name = sanitize_name(req.app_name)

    async def event_stream():
        def log(text: str, level: str = "info"):
            return f"data: {json.dumps({'type':'log','text':text,'level':level})}\n\n"

        def done(file: str, url: str, size_mb: float = 0, extra_files: list = None):
            return f"data: {json.dumps({'type':'done','output_file':file,'download_url':url,'size_mb':size_mb,'extra_files': extra_files or []})}\n\n"

        def err(msg: str):
            return f"data: {json.dumps({'type':'error','message':msg})}\n\n"

        try:
            # ── 0. Pre-flight: check required tools before any subprocess ─────
            pf = run_preflight(req.lang, req.target)
            if not pf.ok:
                for event in preflight_error_events(pf):
                    yield event
                return

            # ── 1. Python → .EXE (PyInstaller) ───────────────────────────────
            if req.lang == "python" and req.target == "exe":
                main_py = ws / "main.py"
                if not main_py.exists():
                    candidates = sorted(ws.glob("*.py"))
                    if not candidates:
                        yield log("⚠️ لا يوجد ملف Python — إنشاء تطبيق تجريبي تلقائياً…", "info")
                        main_py.write_text(
                            f'# {req.app_name} — generated by Axon\n'
                            f'import tkinter as tk\n'
                            f'root = tk.Tk()\n'
                            f'root.title("{req.app_name}")\n'
                            f'root.geometry("480x300")\n'
                            f'tk.Label(root, text="🚀 {req.app_name}", font=("Arial", 24, "bold")).pack(expand=True)\n'
                            f'tk.Label(root, text="Built with Axon", font=("Arial", 11)).pack()\n'
                            f'root.mainloop()\n'
                        )
                        yield log("✅ تم إنشاء main.py تجريبي (tkinter)", "ok")
                    else:
                        main_py = candidates[0]
                yield log(f"✅ ملف الإدخال: {main_py.name}", "ok")

                GUI_IMPORTS = ("tkinter", "PyQt", "PySide", "wx", "kivy", "toga", "pyglet", "pygame")
                src_text = main_py.read_text(encoding="utf-8", errors="replace")
                is_gui = any(lib in src_text for lib in GUI_IMPORTS)
                windowed_flag = "--windowed" if is_gui else "--console"
                yield log(f"{'🖼 GUI detected → --windowed' if is_gui else '⌨️ CLI detected → --console'}", "info")

                req_txt = ws / "requirements.txt"
                if req_txt.exists():
                    yield log("📦 تثبيت المتطلبات…", "cmd")
                    async for line, code in _run_stream(
                        ["python", "-m", "pip", "install", "-r", str(req_txt), "--quiet"], str(ws)
                    ):
                        if line.strip():
                            yield log(line, "info")
                        if code is not None and code != 0:
                            yield log(f"تحذير: فشل تثبيت بعض المتطلبات (exit {code})", "info")

                dist_out  = DIST_DIR / safe_name
                dist_out.mkdir(exist_ok=True)
                build_tmp = dist_out / "_build"
                spec_dir  = dist_out / "_spec"

                project_root = str(Path(__file__).parent.parent.parent)
                cmd = [
                    "python", "-m", "PyInstaller",
                    "--onefile" if req.one_file else "--onedir",
                    "--noconfirm", "--clean",
                    windowed_flag,
                    "--name", safe_name,
                    "--distpath", str(dist_out.resolve()),
                    "--workpath",  str(build_tmp.resolve()),
                    "--specpath",  str(spec_dir.resolve()),
                    str(main_py.resolve()),
                ]
                yield log("$ " + " ".join(cmd[2:]), "cmd")
                yield log("⏳ جاري التجميع — قد يستغرق 1-3 دقائق…", "info")

                rc = None
                async for line, code in _run_stream(cmd, project_root):
                    if code is not None:
                        rc = code
                        break
                    if line.strip():
                        lvl = ("err" if "ERROR" in line.upper()
                               else "ok" if any(w in line.lower() for w in ("completed", "success", "building exe"))
                               else "info")
                        yield log(line, lvl)

                if rc != 0:
                    yield log(f"❌ PyInstaller فشل (exit {rc})", "err")
                    yield err(f"Build failed (exit {rc})")
                    return

                exe = next(
                    (p for ext in (f"{safe_name}.exe", safe_name) for p in [dist_out / ext] if p.exists()),
                    None,
                )
                if not exe:
                    exe = next(iter(dist_out.glob("*.exe")), None)
                if not exe:
                    yield log("❌ لم يُعثر على الملف الناتج", "err")
                    yield err("Output file not found after build.")
                    return

                size_mb = round(exe.stat().st_size / 1024 / 1024, 1)
                yield log(f"✅ تم البناء: {exe.name} ({size_mb} MB)", "ok")

                yield log("📦 بناء مُثبِّت واحد self-extracting…", "info")
                exe_b64 = base64.b64encode(exe.read_bytes()).decode("ascii")

                installer_py = dist_out / f"_installer_{safe_name}.py"
                installer_py.write_text(f"""
import base64, os, sys
from pathlib import Path

APP_NAME  = {repr(req.app_name)}
SAFE_NAME = {repr(safe_name)}
EXE_NAME  = {repr(exe.name)}
EXE_B64   = {repr(exe_b64)}

def create_shortcut(target, shortcut_path, work_dir):
    import subprocess
    ps = f'''$ws=New-Object -COM WScript.Shell
$s=$ws.CreateShortcut("{shortcut_path}")
$s.TargetPath="{target}"
$s.WorkingDirectory="{work_dir}"
$s.Description="{APP_NAME}"
$s.Save()'''
    subprocess.run(["powershell","-NoProfile","-Command",ps], capture_output=True)

def main():
    install_dir = Path(os.environ["LOCALAPPDATA"]) / SAFE_NAME
    install_dir.mkdir(parents=True, exist_ok=True)
    exe_path = install_dir / EXE_NAME
    print(f"[1/4] Installing to {{install_dir}}...")
    exe_path.write_bytes(base64.b64decode(EXE_B64))
    print("[2/4] Files extracted.")
    desktop = Path(os.environ.get("USERPROFILE","")) / "Desktop"
    create_shortcut(str(exe_path), str(desktop / f"{{APP_NAME}}.lnk"), str(install_dir))
    print("[3/4] Desktop shortcut created.")
    start_menu = Path(os.environ["APPDATA"]) / "Microsoft" / "Windows" / "Start Menu" / "Programs" / SAFE_NAME
    start_menu.mkdir(parents=True, exist_ok=True)
    create_shortcut(str(exe_path), str(start_menu / f"{{APP_NAME}}.lnk"), str(install_dir))
    print("[4/4] Start Menu shortcut created.")
    print(f"\\n✅ تم تثبيت {{APP_NAME}} بنجاح!")
    import subprocess
    subprocess.Popen([str(exe_path)], cwd=str(install_dir))

if __name__ == "__main__":
    main()
""", encoding="utf-8")

                installer_exe_name = f"Install_{safe_name}"
                installer_dist = dist_out / "_installer_dist"
                installer_dist.mkdir(exist_ok=True)
                ins_cmd = [
                    "python", "-m", "PyInstaller",
                    "--onefile", "--noconfirm", "--clean", "--console",
                    "--name", installer_exe_name,
                    "--distpath", str(installer_dist.resolve()),
                    "--workpath", str((dist_out / "_ins_build").resolve()),
                    "--specpath", str((dist_out / "_ins_spec").resolve()),
                    str(installer_py.resolve()),
                ]
                yield log("$ PyInstaller installer…", "cmd")
                yield log("⏳ بناء المُثبِّت — دقيقة واحدة…", "info")
                rc2 = None
                async for line, code in _run_stream(ins_cmd, project_root):
                    if code is not None:
                        rc2 = code
                        break
                    if line.strip():
                        yield log(line, "info")

                final_installer = installer_dist / f"{installer_exe_name}.exe"
                if rc2 != 0 or not final_installer.exists():
                    yield log("⚠️ فشل بناء المُثبِّت — سيُقدَّم الـ .exe المباشر", "info")
                    yield done(exe.name, f"/api/package/download/{safe_name}/{exe.name}", size_mb)
                    return

                final_dest = dist_out / final_installer.name
                shutil.copy2(final_installer, final_dest)
                ins_size = round(final_dest.stat().st_size / 1024 / 1024, 1)
                yield log(f"✅ مُثبِّت جاهز: {installer_exe_name}.exe ({ins_size} MB)", "ok")
                yield log("🖱️ نقرة واحدة = تثبيت + اختصار سطح المكتب + قائمة ابدأ + تشغيل فوري", "ok")
                yield done(final_dest.name, f"/api/package/download/{safe_name}/{final_dest.name}", ins_size)

            # ── 2. Python → .APK (Briefcase) ─────────────────────────────────
            elif req.lang == "python" and req.target == "apk":
                yield log("📱 بناء APK حقيقي باستخدام BeeWare Briefcase…", "cmd")
                bf_dir  = DIST_DIR / f"{safe_name}_briefcase"
                bf_dir.mkdir(exist_ok=True)
                src_pkg = bf_dir / "src" / safe_name.lower()
                src_pkg.mkdir(parents=True, exist_ok=True)
                for f in ws.glob("*.py"):
                    shutil.copy2(f, src_pkg / f.name)
                mp = src_pkg / "main.py"
                if mp.exists():
                    mp.rename(src_pkg / "__main__.py")
                (src_pkg / "__init__.py").touch()

                pyproject = f"""[tool.briefcase]
project_name = "{req.app_name}"
bundle = "com.example"
version = "{req.app_version}"
url = "https://example.com"
license.file = "LICENSE"
author = "Axon"
author_email = "ai@studio.com"

[tool.briefcase.app.{safe_name.lower()}]
formal_name = "{req.app_name}"
description = "Built with Axon"
icon = "icon"
sources = ["src/{safe_name.lower()}"]
requires = ["toga"]

[tool.briefcase.app.{safe_name.lower()}.android]
requires = ["toga-android"]
base_theme = "@style/Theme.AppCompat.Light.DarkActionBar"
"""
                (bf_dir / "pyproject.toml").write_text(pyproject)
                (bf_dir / "LICENSE").write_text("MIT License")
                yield log("✅ هيكل مشروع Briefcase جاهز", "ok")

                rc_bf, _, _ = await rt_process.run_process(
                    ["python", "-m", "briefcase", "--version"], timeout=10.0
                )
                if rc_bf != 0:
                    yield log("📦 تثبيت Briefcase…", "cmd")
                    async for line, code in _run_stream(
                        ["python", "-m", "pip", "install", "briefcase", "--quiet"], str(bf_dir)
                    ):
                        if line.strip():
                            yield log(line, "info")

                yield log("$ briefcase create android", "cmd")
                yield log("⏳ إعداد مشروع Android (قد يُحمِّل Android SDK في المرة الأولى ~5 دقائق)…", "info")
                async for line, code in _run_stream(
                    ["python", "-m", "briefcase", "create", "android", "--no-input"], str(bf_dir)
                ):
                    if code is not None:
                        if code != 0:
                            yield log(f"❌ briefcase create فشل (exit {code})", "err")
                            yield err(f"briefcase create failed (exit {code})")
                            return
                        break
                    if line.strip():
                        lvl = "err" if "error" in line.lower() else "ok" if "success" in line.lower() else "info"
                        yield log(line, lvl)

                yield log("$ briefcase build android", "cmd")
                yield log("⏳ جاري تجميع APK…", "info")
                async for line, code in _run_stream(
                    ["python", "-m", "briefcase", "build", "android", "--no-input"], str(bf_dir)
                ):
                    if code is not None:
                        if code != 0:
                            yield log(f"❌ briefcase build فشل (exit {code})", "err")
                            yield err(f"briefcase build failed (exit {code})")
                            return
                        break
                    if line.strip():
                        lvl = "err" if "error" in line.lower() else "ok" if "apk" in line.lower() or "success" in line.lower() else "info"
                        yield log(line, lvl)

                apk_files = list(bf_dir.rglob("*.apk"))
                if not apk_files:
                    yield log("❌ لم يُعثر على APK بعد البناء", "err")
                    yield err("APK not found after build.")
                    return

                apk = apk_files[0]
                out_apk = DIST_DIR / safe_name / apk.name
                (DIST_DIR / safe_name).mkdir(exist_ok=True)
                shutil.copy2(apk, out_apk)
                size_mb = round(out_apk.stat().st_size / 1024 / 1024, 1)
                yield log(f"✅ APK جاهز: {out_apk.name} ({size_mb} MB)", "ok")
                yield done(out_apk.name, f"/api/package/download/{safe_name}/{out_apk.name}", size_mb)

            # ── 3. Web → .APK (Capacitor + Gradle) ───────────────────────────
            elif req.lang == "web" and req.target == "apk":
                yield log("🌐 بناء APK من تطبيق ويب باستخدام Capacitor + Gradle…", "cmd")
                cap_dir = DIST_DIR / f"{safe_name}_capacitor"
                cap_dir.mkdir(exist_ok=True)
                html_files = list(ws.glob("*.html"))
                entry = html_files[0].name if html_files else "index.html"
                if not (ws / entry).exists():
                    (ws / entry).write_text(
                        f"<!DOCTYPE html><html><head><meta charset='utf-8'><title>{req.app_name}</title></head>"
                        f"<body><h1>{req.app_name}</h1></body></html>"
                    )
                dist_web = cap_dir / "dist"
                dist_web.mkdir(exist_ok=True)
                for f in ws.iterdir():
                    if f.is_file() and f.suffix in (".html", ".css", ".js", ".png", ".jpg", ".svg", ".ico"):
                        shutil.copy2(f, dist_web / f.name)

                (cap_dir / "package.json").write_text(json.dumps({
                    "name": safe_name.lower(), "version": req.app_version,
                    "scripts": {"build": "echo done"},
                    "dependencies": {"@capacitor/core": "6.x", "@capacitor/android": "6.x", "@capacitor/cli": "6.x"},
                }, indent=2))
                (cap_dir / "capacitor.config.json").write_text(json.dumps({
                    "appId": f"com.aistudio.{safe_name.lower()}",
                    "appName": req.app_name,
                    "webDir": "dist",
                }, indent=2))

                yield log("📦 npm install…", "cmd")
                async for line, code in _run_stream(["npm", "install", "--silent"], str(cap_dir)):
                    if code is not None:
                        if code != 0:
                            yield log(f"npm install فشل (exit {code})", "err")
                            yield err("npm install failed")
                            return
                        break
                    if line.strip():
                        yield log(line, "info")

                for cap_cmd in (["npx", "cap", "add", "android"], ["npx", "cap", "sync", "android"]):
                    yield log(f"$ {' '.join(cap_cmd[1:])}", "cmd")
                    async for line, code in _run_stream(cap_cmd, str(cap_dir)):
                        if code is not None:
                            if code != 0:
                                yield log(f"{cap_cmd[2]} فشل (exit {code})", "err")
                                yield err(f"{cap_cmd[2]} failed")
                                return
                            break
                        if line.strip():
                            yield log(line, "info")

                gradlew = cap_dir / "android" / "gradlew.bat"
                yield log("$ gradlew assembleDebug", "cmd")
                yield log("⏳ جاري Gradle build (قد يستغرق 3-8 دقائق في المرة الأولى)…", "info")
                async for line, code in _run_stream([str(gradlew), "assembleDebug"], str(cap_dir / "android")):
                    if code is not None:
                        if code != 0:
                            yield log(f"Gradle فشل (exit {code})", "err")
                            yield err(f"Gradle build failed (exit {code})")
                            return
                        break
                    if line.strip():
                        lvl = "err" if "error" in line.lower() else "ok" if "build successful" in line.lower() else "info"
                        yield log(line, lvl)

                apk_files = list((cap_dir / "android").rglob("*debug*.apk"))
                if not apk_files:
                    yield log("❌ لم يُعثر على APK", "err")
                    yield err("APK not found after Gradle build.")
                    return

                apk = apk_files[0]
                out_apk = DIST_DIR / safe_name / apk.name
                (DIST_DIR / safe_name).mkdir(exist_ok=True)
                shutil.copy2(apk, out_apk)
                size_mb = round(out_apk.stat().st_size / 1024 / 1024, 1)
                yield log(f"✅ APK جاهز: {out_apk.name} ({size_mb} MB)", "ok")
                yield done(out_apk.name, f"/api/package/download/{safe_name}/{out_apk.name}", size_mb)

            # ── 4. Web → .EXE (Electron Builder) ─────────────────────────────
            elif req.lang == "electron" and req.target == "exe":
                yield log("⚡ بناء .EXE باستخدام Electron Builder…", "cmd")
                el_dir = DIST_DIR / f"{safe_name}_electron"
                el_dir.mkdir(exist_ok=True)
                for f in ws.iterdir():
                    if f.is_file():
                        shutil.copy2(f, el_dir / f.name)

                html_files = list(el_dir.glob("*.html"))
                entry = html_files[0].name if html_files else "index.html"
                if not (el_dir / entry).exists():
                    (el_dir / entry).write_text(
                        f"<!DOCTYPE html><html><head><meta charset='utf-8'><title>{req.app_name}</title></head>"
                        f"<body style='font-family:sans-serif;padding:40px;background:#1a1a2e;color:#fff'>"
                        f"<h1>{req.app_name}</h1><p>Powered by Axon</p></body></html>"
                    )

                (el_dir / "main.js").write_text(
                    f"const {{app, BrowserWindow}} = require('electron')\n"
                    f"function createWindow() {{\n"
                    f"  const win = new BrowserWindow({{\n"
                    f"    width: 1200, height: 800,\n"
                    f"    webPreferences: {{nodeIntegration: false, contextIsolation: true}}\n"
                    f"  }})\n"
                    f"  win.loadFile('{entry}')\n"
                    f"  win.setTitle('{req.app_name}')\n"
                    f"}}\n"
                    f"app.whenReady().then(createWindow)\n"
                    f"app.on('window-all-closed', () => {{ if (process.platform !== 'darwin') app.quit() }})\n"
                )
                (el_dir / "package.json").write_text(json.dumps({
                    "name": safe_name.lower(), "version": req.app_version,
                    "description": req.app_name, "main": "main.js",
                    "scripts": {"start": "electron .", "dist": "electron-builder --win --x64"},
                    "build": {
                        "appId": f"com.aistudio.{safe_name.lower()}",
                        "productName": req.app_name,
                        "win": {"target": [{"target": "nsis", "arch": ["x64"]}], "icon": None},
                        "nsis": {"oneClick": True, "perMachine": False},
                        "files": ["**/*", "!node_modules/**"],
                    },
                    "devDependencies": {"electron": "^32.0.0", "electron-builder": "^25.0.0"},
                }, indent=2))

                yield log("📦 npm install…", "cmd")
                async for line, code in _run_stream(["npm", "install", "--silent"], str(el_dir)):
                    if code is not None:
                        if code != 0:
                            yield log(f"npm install فشل (exit {code})", "err")
                            yield err("npm install failed")
                            return
                        break
                    if line.strip():
                        yield log(line, "info")

                yield log("$ npm run dist  (Electron Builder NSIS)", "cmd")
                yield log("⏳ جاري البناء — قد يستغرق 3-10 دقائق…", "info")
                async for line, code in _run_stream(["npm", "run", "dist"], str(el_dir)):
                    if code is not None:
                        if code != 0:
                            yield log(f"❌ electron-builder فشل (exit {code})", "err")
                            yield err(f"electron-builder failed (exit {code})")
                            return
                        break
                    if line.strip():
                        lvl = "err" if "error" in line.lower() else "ok" if "target=" in line.lower() or "packag" in line.lower() else "info"
                        yield log(line, lvl)

                dist_el = el_dir / "dist"
                exe_files = list(dist_el.glob("**/*.exe")) if dist_el.exists() else []
                if not exe_files:
                    yield log("❌ لم يُعثر على .exe", "err")
                    yield err("EXE not found after build.")
                    return

                exe = exe_files[0]
                out_exe = DIST_DIR / safe_name / exe.name
                (DIST_DIR / safe_name).mkdir(exist_ok=True)
                shutil.copy2(exe, out_exe)
                size_mb = round(out_exe.stat().st_size / 1024 / 1024, 1)
                yield log(f"✅ مُثبِّت Windows جاهز: {out_exe.name} ({size_mb} MB)", "ok")
                yield done(out_exe.name, f"/api/package/download/{safe_name}/{out_exe.name}", size_mb)

            else:
                yield log(f"التركيبة {req.lang}→{req.target} غير مدعومة حالياً.", "err")
                yield err("Unsupported combination.")

        except FileNotFoundError as e:
            import logging
            logging.getLogger(__name__).exception("Build FileNotFoundError (tool missing from PATH)")
            tool = str(e).split("'")[1] if "'" in str(e) else str(e)
            yield log(f"❌ الأداة غير موجودة: {tool}", "err")
            yield sse_error(
                category="missing_runtime",
                message=f"Build tool not found: {tool}",
                fix=[
                    f"Install {tool} and ensure it is on PATH",
                    "Restart the server after installation so the runtime registry refreshes",
                ],
                severity="high",
                recoverable=False,
                missing_tool=tool,
            )
        except Exception as e:
            import logging
            logging.getLogger(__name__).exception("Package build error")
            yield log(f"❌ خطأ غير متوقع: {type(e).__name__}: {e}", "err")
            yield err(f"{type(e).__name__}: {e}")

    return StreamingResponse(event_stream(), media_type="text/event-stream",
                             headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"})


@router.get("/api/package/download/{folder}/{filename}")
async def download_package(folder: str, filename: str):
    safe_f = sanitize_name(folder)
    safe_n = sanitize_name(filename.rsplit(".", 1)[0]) + ("." + filename.rsplit(".", 1)[1] if "." in filename else "")
    safe_n = safe_n.replace("..", "")
    path = (DIST_DIR / safe_f / safe_n).resolve()
    if not str(path).startswith(str(DIST_DIR.resolve())):
        from fastapi import HTTPException
        raise HTTPException(400, "Invalid path")
    if not path.exists():
        from fastapi import HTTPException
        raise HTTPException(404, "File not found")
    ext = path.suffix.lower()
    media = ("application/vnd.android.package-archive" if ext == ".apk"
             else "application/zip" if ext == ".zip"
             else "application/octet-stream")
    return FileResponse(str(path), media_type=media, filename=path.name,
                        headers={"Content-Disposition": f'attachment; filename="{path.name}"'})
