"""add content strategy, pillars, generations, items

Revision ID: 7a3f568181a7
Revises: a922fafbef6e
Create Date: 2026-08-11 15:17:54.000473
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a3f568181a7'
down_revision: Union[str, None] = 'a922fafbef6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_strategies',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('business_description', sa.Text(), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=False),
    sa.Column('goals', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=80), nullable=False),
    sa.Column('language', sa.String(length=40), nullable=False),
    sa.Column('brand_voice', sa.Text(), nullable=False),
    sa.Column('content_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_strategies_organization_id'), 'content_strategies', ['organization_id'], unique=False)
    op.create_table('content_generations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('generation_type', sa.Enum('IDEAS', 'POST', name='content_generation_type'), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('SUCCEEDED', 'FAILED', name='content_generation_status'), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['content_strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_generations_organization_id'), 'content_generations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_content_generations_strategy_id'), 'content_generations', ['strategy_id'], unique=False)
    op.create_table('content_pillars',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['content_strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_pillars_organization_id'), 'content_pillars', ['organization_id'], unique=False)
    op.create_index(op.f('ix_content_pillars_strategy_id'), 'content_pillars', ['strategy_id'], unique=False)
    op.create_table('content_items',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('generation_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('hashtags', sa.ARRAY(sa.String(length=80)), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'ARCHIVED', name='content_item_status'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['content_generations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['content_strategies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_items_organization_id'), 'content_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_content_items_strategy_id'), 'content_items', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_items_strategy_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_organization_id'), table_name='content_items')
    op.drop_table('content_items')
    sa.Enum(name='content_item_status').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_content_pillars_strategy_id'), table_name='content_pillars')
    op.drop_index(op.f('ix_content_pillars_organization_id'), table_name='content_pillars')
    op.drop_table('content_pillars')
    op.drop_index(op.f('ix_content_generations_strategy_id'), table_name='content_generations')
    op.drop_index(op.f('ix_content_generations_organization_id'), table_name='content_generations')
    op.drop_table('content_generations')
    sa.Enum(name='content_generation_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='content_generation_type').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_content_strategies_organization_id'), table_name='content_strategies')
    op.drop_table('content_strategies')
    # ### end Alembic commands ###
